### ISSUE TITLE
The Law of Leaky Abstractions - Joel Spolsky - November 2012

### ISSUE THREAD

**Issue by jasper07** [qmacro/tech-aloud#13]
https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/

**Comment by qmacro** [comment]
This post is 17 years old, but still totally relevant today in what it teaches us - that while we construct new software architectures on top of older ones, things are still hard - harder, even - when problems occur. And there's a great line in this article that is worth quoting here: "_... abstractions save us time working, but they don’t save us time learning_".

**Comment by jasper07** [comment]
"... abstractions save us time working, but they don’t save us time learning", that was my takeaway also, Joel's comment about generated code was on the money, to paraphrase if you generate something in VB and the code breaks, no use getting a VB coder to fix as they wont have learnt the underlying abstraction, for me this sums up Fiori Elements and CAPM to an extent, abstractions in code are examples of the pareto principle IMO
